import random
from mad import input_template_one, input_template_two
print("Hi its's Mad Libs game")
print("================")

# Three different templates for the Mad Libs game
template_1 = ("1: It was about (Number) (Measure of time) ago when I arrived at the hospital in a (Mode of Transportation). The hospital is a/an (Adjective) place, there are a lot of (Adjective2) (Noun) here. There are nurses here who have (Color) (Part of the Body ). If someone wants to come into my room I told them that they have to (Verb) first. I’ve decorated my room with (Number2) (Noun2). Today I talked to a doctor and they were wearing a (Noun3) on their ( Part of the Body 2). I heard that all doctors (Verb) (Noun4) every day for breakfast. The most ( Adjective3) thing about being in the hospital is the (Silly Word ) (Noun) !")
template_2 = ("2: This weekend I am going camping with ( Proper Noun (Person’s Name)). I packed my lantern, sleeping bag, and (Noun). I am so (Adjective (Feeling)) to (Verb) in a tent. I am (Adjective (Feeling) 2) we might see a(n) (Animal), I hear they’re kind of dangerous. While we’re camping, we are going to hike, fish, and (Verb2). I have heard that the (Color) lake is great for ( Verb (ending in ing) ). Then we will (Adverb (ending in ly)) hike through the forest for (Number) (Measure of Time). If I see a (Color) (Animal) while hiking, I am going to bring it home as a pet! At night we will tell (Number) (Silly Word) stories and roast (Noun2) around the campfire!!")
template_3 =("3: Dear (Proper Noun (Person’s Name) ), I am writing to you from a (Adjective) castle in an enchanted forest. I found myself here one day after going for a ride on a (Color) (Animal) in (Place). There are (Adjective2) (Magical Creature (Plural)) and (Adjective3) (Magical Creature (Plural)2) here! In the ( Room in a House) there is a pool full of (Noun). I fall asleep each night on a (Noun2) of (Noun(Plural)3) and dream of (Adjective4) ( Noun (Plural)4). It feels as though I have lived here for (Number) ( Measure of time). I hope one day you can visit, although the only way to get here now is (Verb (ending in ing)) on a (Adjective5) (Noun5)!!")

# Randomly select a template
random_numbers = random.randint(1,3)

# Display the selected template and prompt for user input accordingly
if (random_numbers == 1):
    print("Your template is ===>>> " + template_1)
    print("================================")
    input_template_one()
elif (random_numbers == 2):
    print("Your template is ===>>> " + template_2) 
    print("================================")
    input_template_two()
elif (random_numbers == 3):
    print("Your template is ===>>> " + template_3)
    print("================================")
    name = input("Input Person Name :")
    adjective_1 = input("Input adjective: ")
    color = input("Input a color: ")
    animal = input("Input an animal:")
    place = input("Input a place: ")
    adjective_2 = input("Input adjective: ")
    magical_creature = input("Input Magical Creature (Plural): ")
    adjective_3 = input("Input adjective: ")
    magical_creature2 = input("Input Magical Creature (Plural): ")
    room_in_a_house = input("Input Room in a House: ")
    noun = input("Input noun: ")
    noun2 = input("Input noun: ")
    noun_plural = input("Input noun (plural): ")
    adjective_4 = input("Input adjective: ")
    noun_plural2 = input("Input noun (plural): ")
    number = input("Input a number: ")
    measure_of_time = ("Measure of time: ")
    verb_ing = input("Input a verb + ing: ")
    adjective_5 = input("Input adjective: ")
    noun3 = input("Input noun: ")

    # Display the entered story
    print("================================")
    print("The story you entered...")
    print("================================")
    print("Input Person Name :" + name)
    print("Input adjective: " + adjective_1)
    print("Input a color: " + color)
    print("Input an animal: " + animal)
    print("Input a place: " + place)
    print("Input adjective: " + adjective_2)
    print("Input Magical Creature (Plural): " + magical_creature)
    print("Input adjective: " + adjective_3)
    print("Magical Creature (Plural): " + magical_creature2)
    print("Input Room in a House: " + room_in_a_house)
    print("Input noun: " + noun)
    print("Input noun: " + noun2)
    print("Input noun (plural): " + noun_plural)
    print("Input adjective: " + adjective_4)
    print("Input noun (plural): " + noun_plural2)
    print("Input a number: " + number)
    print("Measure of time: " + measure_of_time)
    print("Input a verb + ing: " + verb_ing)
    print("Input adjective: " + adjective_5)
    print("Input noun: " + noun3)
    print("================================")
