def input_template_one():
    number = input("Input a number: ")
    measure_of_time = input ("Measure of time: ")
    mode_of_trasportation = input("Mode of Transportation: ")
    adjective = input("Input adjective: ")
    adjective2 = input("Input adjective: ")
    noun = input("Input noun: ")
    color = input("Input a color: ")
    part_of_the_body = input("Input Part of the Body: ")
    verb = input("Input a verb: ")
    number2 = input("Input a number: ")
    noun2 = input("Input noun: ")
    noun3 = input("Input noun: ")
    part_of_the_body2 = input("Input Part of the Body: ")
    verb2 = input("Input a verb: ")
    noun4 = input("Input noun: ")
    adjective3 = input("Input adjective: ")
    silly_word = input("Input a silly word: ")
    noun5 = input("Input noun: ")
    print("================================")
    print("The story you entered...")
    print("Input a number: " + number)
    print("Measure of time: " + measure_of_time)
    print("Mode of Trasportation : " + mode_of_trasportation)
    print("Input adjective: " + adjective)
    print("Input adjective: " + adjective2)
    print("Input noun: " + noun)
    print("Input a color: " + color)
    print("Input Part of the Body: " + part_of_the_body)
    print("Input a verb: " + verb)
    print("Input a number: " + number2)
    print("Input noun: " + noun2)
    print("Input noun: " + noun3)
    print("Input Part of the Body: " + part_of_the_body2)
    print("Input a verb: " + verb2)
    print("Input noun: " + noun4)
    print("Input adjective: " + adjective3)
    print("Input a silly word: " + silly_word)
    print("Input noun" + noun5)

def input_template_two():
    name = input("Input Person Name :")
    noun = input("Input noun: ")
    adjective_1 = input("Input adjective (feeling): ")
    verb = input("Input verb: ")
    adjective_2 = input("Input adjective (feeling): ")
    animal = input("Input an animal: ")
    verb2 = input("Input a verb: ")
    color = input("Input a color: ")
    verb_ing = input("Input a verb + ing: ")
    adverb_ly = input("Input a adverb + ly: ")
    number = input("Input a number: ")
    measure_of_time = ("Measure of time: ")
    color2 = input("Input a color: ")
    animal2 = input("Input an animal: ")
    number2 = input("Input a number: ")
    silly_word = input("Input a silly word: ")
    noun2 = input("Input noun: ")
    print("================================")
    print("The story you entered...")
    print("Input Person Name :" + name)
    print("Input noun: " + noun)
    print("Input adjective (feeling): " + adjective_1)
    print("Input verb: " + verb)
    print("Input adjective (feeling): " + adjective_2)
    print("Input an animal: " + animal)
    print("Input a verb: " + verb2)
    print("Input a color: " + color)
    print("Input a verb + ing: " + verb_ing)
    print("Input a adverb + ly: " + adverb_ly)
    print("Input a number: " + number)
    print("Measure of time: " + measure_of_time)
    print("Input a color: " + color2)
    print("Input an animal: " + animal2)
    print("Input a number: " + number2)
    print("INput a silly word: " + silly_word)
    print("Input noun: " + noun2)
    print("================================")
